shark_species = {
    'Great white shark': 'Great white shark',
    'Hammerhead shark': 'Hammerhead shark',
    'Tiger shark': 'Tiger shark',
    'Bull shark': 'Bull shark',
    'Whale shark': 'Whale shark',
    'Mako shark': 'Mako shark',
    'Lemon shark': 'Lemon shark',
    'Blacktip shark': 'Blacktip shark',
    'Grey reef shark': 'Grey reef shark',
    'Caribbean reef shark': 'Caribbean reef shark',
    'Whitetip reef shark': 'Whitetip reef shark',
    'Sand tiger shark': 'Sand tiger shark',
    'Goblin shark': 'Goblin shark',
    'Thresher shark': 'Thresher shark',
    'Basking shark': 'Basking shark',
    'Oceanic whitetip shark': 'Oceanic whitetip shark',
    'Blue shark': 'Blue shark',
    'Zambezi shark': 'Zambezi shark',
    'Dusky shark': 'Dusky shark',
    'Nurse shark': 'Nurse shark',
    'Spiny dogfish shark': 'Spiny dogfish shark',
    'Scalloped hammerhead shark': 'Scalloped hammerhead shark',
    'Smooth hammerhead shark': 'Smooth hammerhead shark',
    'Porbeagle shark': 'Porbeagle shark',
    'Shortfin mako shark': 'Shortfin mako shark',
    'Longfin mako shark': 'Longfin mako shark',
    'Greenland shark': 'Greenland shark',
    'Pygmy shark': 'Pygmy shark',
    'Elephant shark': 'Elephant shark',
    'Pelagic thresher shark': 'Pelagic thresher shark',
    'Copper shark': 'Copper shark',
    'Galapagos shark': 'Galapagos shark'
}